### ISSUE TITLE
Description not enough

### ISSUE THREAD

**Issue by ugurdogrusoz** [dcaneren/CS319-Section-2-Group-F#1]
You should expand your project description. Also make sure to mention (with references) if there are any similar publicly available software and how your differs from those.

**Comment by ugurdogrusoz** [comment]
Why didn't you guys address this issue at all?

**Comment by dcaneren** [comment]
We did extend the description, if it is not sufficient enough as it is now, we are waiting for your response to extend it more.

**Comment by ugurdogrusoz** [comment]
Thanks @dcaneren . This issue is obsolete at the moment since analysis report started and requirements were elicited anyway. In any case, when you address/resolve an issue, you should assign it back to the person who created it, so they can verify and close it.
